using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using RustCUIBuilder.Runtime.Core.Models;

namespace RustCUIBuilder.Runtime.Core.Serialization
{
    public class CodeGeneratorOptions
    {
        public string MethodName { get; set; } = "DrawUI";
        public string ContainerVariableName { get; set; } = "container";
        public string PlayerVariableName { get; set; } = "player";
        public string MainPanelConstantName { get; set; } = "MainUiPanel";
        public bool IncludeMethodWrapper { get; set; } = true;
        public bool IncludeCommandHook { get; set; } = true;
        public bool IncludeUnloadHook { get; set; } = true;
        public bool UseHighLevelPresets { get; set; } = true; // Use CuiPanel, CuiLabel, CuiButton where applicable
    }

    /// <summary>
    /// Generates clean, deterministic, valid Oxide/uMod C# plugin code.
    /// Employs CuiElementContainer with high-level CuiPanel, CuiLabel, CuiButton, and individual CuiElement blocks.
    /// </summary>
    public static class CuiCodeGenerator
    {
        public static string GeneratePluginCode(CuiDocument doc, CodeGeneratorOptions options = null)
        {
            options = options ?? new CodeGeneratorOptions();
            var sb = new StringBuilder(4096);

            string rootPanelName = doc.Elements.FirstOrDefault(e => e.Components.Any(c => c is CuiNeedsCursorComponent || c is CuiImageComponent))?.Name ?? "MainPanel";

            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine("//  <auto-generated>");
            sb.AppendLine($"//      Rust Oxide CUI Builder Generated Code");
            sb.AppendLine($"//      Rust Protocol: {doc.RustProtocol} | Elements: {doc.Elements.Count}");
            sb.AppendLine("//  </auto-generated>");
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Oxide.Core;");
            sb.AppendLine("using Oxide.Game.Rust.Cui;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.UI;");
            sb.AppendLine();

            if (options.IncludeMethodWrapper)
            {
                sb.AppendLine($"private const string {options.MainPanelConstantName} = \"{rootPanelName}\";");
                sb.AppendLine();
                sb.AppendLine($"private void {options.MethodName}(BasePlayer {options.PlayerVariableName})");
                sb.AppendLine("{");
                sb.AppendLine($"    if ({options.PlayerVariableName} == null || !{options.PlayerVariableName}.IsConnected) return;");
                sb.AppendLine();
                sb.AppendLine($"    // Clean up any existing UI to avoid stacking");
                sb.AppendLine($"    CuiHelper.DestroyUi({options.PlayerVariableName}, {options.MainPanelConstantName});");
                sb.AppendLine();
                sb.AppendLine($"    var {options.ContainerVariableName} = new CuiElementContainer();");
                sb.AppendLine();
            }

            string indent = options.IncludeMethodWrapper ? "    " : "";

            foreach (var elem in doc.Elements)
            {
                GenerateElementBlock(sb, elem, options, indent);
                sb.AppendLine();
            }

            if (options.IncludeMethodWrapper)
            {
                sb.AppendLine($"    // Send UI container to player");
                sb.AppendLine($"    CuiHelper.AddUi({options.PlayerVariableName}, {options.ContainerVariableName});");
                sb.AppendLine("}");

                if (options.IncludeCommandHook)
                {
                    sb.AppendLine();
                    sb.AppendLine($"[ConsoleCommand(\"myui.close\")]");
                    sb.AppendLine($"private void CommandCloseUI(ConsoleSystem.Arg arg)");
                    sb.AppendLine("{");
                    sb.AppendLine($"    BasePlayer player = arg.Player();");
                    sb.AppendLine($"    if (player == null) return;");
                    sb.AppendLine($"    CuiHelper.DestroyUi(player, {options.MainPanelConstantName});");
                    sb.AppendLine("}");
                }

                if (options.IncludeUnloadHook)
                {
                    sb.AppendLine();
                    sb.AppendLine("private void Unload()");
                    sb.AppendLine("{");
                    sb.AppendLine("    foreach (BasePlayer player in BasePlayer.activePlayerList)");
                    sb.AppendLine("    {");
                    sb.AppendLine("        if (player != null && player.IsConnected)");
                    sb.AppendLine("        {");
                    sb.AppendLine($"            CuiHelper.DestroyUi(player, {options.MainPanelConstantName});");
                    sb.AppendLine("        }");
                    sb.AppendLine("    }");
                    sb.AppendLine("}");
                }
            }

            return sb.ToString();
        }

        private static void GenerateElementBlock(StringBuilder sb, CuiElementNode elem, CodeGeneratorOptions options, string indent)
        {
            var rect = elem.GetComponent<CuiRectTransformComponent>() ?? new CuiRectTransformComponent();
            var img = elem.GetComponent<CuiImageComponent>();
            var raw = elem.GetComponent<CuiRawImageComponent>();
            var text = elem.GetComponent<CuiTextComponent>();
            var btn = elem.GetComponent<CuiButtonComponent>();
            var cursor = elem.GetComponent<CuiNeedsCursorComponent>();
            var kb = elem.GetComponent<CuiNeedsKeyboardComponent>();

            // Check if it fits CuiPanel pattern
            if (options.UseHighLevelPresets && btn == null && text == null && (img != null || raw != null))
            {
                sb.AppendLine($"{indent}{options.ContainerVariableName}.Add(new CuiPanel");
                sb.AppendLine($"{indent}{{");
                if (img != null)
                {
                    sb.Append($"{indent}    Image = {{ Color = \"{img.Color}\"");
                    if (!string.IsNullOrEmpty(img.Sprite) && img.Sprite != "assets/content/ui/ui.background.tile.psd") sb.Append($", Sprite = \"{img.Sprite}\"");
                    if (!string.IsNullOrEmpty(img.Material)) sb.Append($", Material = \"{img.Material}\"");
                    if (img.ItemId != 0) sb.Append($", ItemId = {img.ItemId}");
                    sb.AppendLine(" },");
                }
                else if (raw != null)
                {
                    sb.Append($"{indent}    RawImage = {{ Color = \"{raw.Color}\"");
                    if (!string.IsNullOrEmpty(raw.Url)) sb.Append($", Url = \"{raw.Url}\"");
                    if (!string.IsNullOrEmpty(raw.SteamId)) sb.Append($", SteamId = \"{raw.SteamId}\"");
                    if (!string.IsNullOrEmpty(raw.Material)) sb.Append($", Material = \"{raw.Material}\"");
                    sb.AppendLine(" },");
                }

                sb.AppendLine($"{indent}    RectTransform = {{ AnchorMin = \"{rect.AnchorMin}\", AnchorMax = \"{rect.AnchorMax}\", OffsetMin = \"{rect.OffsetMin}\", OffsetMax = \"{rect.OffsetMax}\" }},");
                if (cursor != null) sb.AppendLine($"{indent}    CursorEnabled = true,");
                if (kb != null) sb.AppendLine($"{indent}    KeyboardEnabled = true,");
                if (elem.FadeOut > 0.001f) sb.AppendLine($"{indent}    FadeOut = {elem.FadeOut}f,");
                sb.AppendLine($"{indent}}}, \"{elem.Parent}\", \"{elem.Name}\");");
                return;
            }

            // Check if it fits CuiButton pattern
            if (options.UseHighLevelPresets && btn != null)
            {
                sb.AppendLine($"{indent}{options.ContainerVariableName}.Add(new CuiButton");
                sb.AppendLine($"{indent}{{");
                sb.Append($"{indent}    Button = {{ Command = \"{btn.Command}\", Color = \"{btn.Color}\"");
                if (!string.IsNullOrEmpty(btn.Close)) sb.Append($", Close = \"{btn.Close}\"");
                if (!string.IsNullOrEmpty(btn.Material)) sb.Append($", Material = \"{btn.Material}\"");
                sb.AppendLine(" },");

                sb.AppendLine($"{indent}    RectTransform = {{ AnchorMin = \"{rect.AnchorMin}\", AnchorMax = \"{rect.AnchorMax}\", OffsetMin = \"{rect.OffsetMin}\", OffsetMax = \"{rect.OffsetMax}\" }},");
                if (text != null)
                {
                    sb.AppendLine($"{indent}    Text = {{ Text = \"{EscapeCSharp(text.Text)}\", FontSize = {text.FontSize}, Align = TextAnchor.{text.Align}, Color = \"{text.Color}\" }},");
                }
                if (elem.FadeOut > 0.001f) sb.AppendLine($"{indent}    FadeOut = {elem.FadeOut}f,");
                sb.AppendLine($"{indent}}}, \"{elem.Parent}\", \"{elem.Name}\");");
                return;
            }

            // Check if it fits CuiLabel pattern
            if (options.UseHighLevelPresets && text != null && img == null && btn == null && raw == null)
            {
                sb.AppendLine($"{indent}{options.ContainerVariableName}.Add(new CuiLabel");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    Text = {{ Text = \"{EscapeCSharp(text.Text)}\", FontSize = {text.FontSize}, Align = TextAnchor.{text.Align}, Color = \"{text.Color}\" }},");
                sb.AppendLine($"{indent}    RectTransform = {{ AnchorMin = \"{rect.AnchorMin}\", AnchorMax = \"{rect.AnchorMax}\", OffsetMin = \"{rect.OffsetMin}\", OffsetMax = \"{rect.OffsetMax}\" }},");
                if (elem.FadeOut > 0.001f) sb.AppendLine($"{indent}    FadeOut = {elem.FadeOut}f,");
                sb.AppendLine($"{indent}}}, \"{elem.Parent}\", \"{elem.Name}\");");
                return;
            }

            // General CuiElement with multiple components
            sb.AppendLine($"{indent}{options.ContainerVariableName}.Add(new CuiElement");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    Name = \"{elem.Name}\",");
            sb.AppendLine($"{indent}    Parent = \"{elem.Parent}\",");
            if (!string.IsNullOrEmpty(elem.DestroyUi)) sb.AppendLine($"{indent}    DestroyUi = \"{elem.DestroyUi}\",");
            if (elem.FadeOut > 0.001f) sb.AppendLine($"{indent}    FadeOut = {elem.FadeOut}f,");
            if (elem.Update) sb.AppendLine($"{indent}    Update = true,");
            sb.AppendLine($"{indent}    Components =");
            sb.AppendLine($"{indent}    {{");

            foreach (var c in elem.Components)
            {
                GenerateComponentSnippet(sb, c, indent + "        ");
            }

            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}});");
        }

        private static void GenerateComponentSnippet(StringBuilder sb, ICuiComponent c, string indent)
        {
            switch (c)
            {
                case CuiRectTransformComponent rect:
                    sb.AppendLine($"{indent}new CuiRectTransformComponent {{ AnchorMin = \"{rect.AnchorMin}\", AnchorMax = \"{rect.AnchorMax}\", OffsetMin = \"{rect.OffsetMin}\", OffsetMax = \"{rect.OffsetMax}\" }},");
                    break;
                case CuiTextComponent text:
                    sb.AppendLine($"{indent}new CuiTextComponent {{ Text = \"{EscapeCSharp(text.Text)}\", FontSize = {text.FontSize}, Align = TextAnchor.{text.Align}, Color = \"{text.Color}\" }},");
                    break;
                case CuiImageComponent img:
                    sb.AppendLine($"{indent}new CuiImageComponent {{ Color = \"{img.Color}\", Sprite = \"{img.Sprite}\" }},");
                    break;
                case CuiRawImageComponent raw:
                    sb.AppendLine($"{indent}new CuiRawImageComponent {{ Color = \"{raw.Color}\", Url = \"{raw.Url}\" }},");
                    break;
                case CuiButtonComponent btn:
                    sb.AppendLine($"{indent}new CuiButtonComponent {{ Command = \"{btn.Command}\", Close = \"{btn.Close}\", Color = \"{btn.Color}\" }},");
                    break;
                case CuiInputFieldComponent input:
                    sb.AppendLine($"{indent}new CuiInputFieldComponent {{ Text = \"{EscapeCSharp(input.Text)}\", FontSize = {input.FontSize}, Command = \"{input.Command}\" }},");
                    break;
                case CuiCountdownComponent count:
                    sb.AppendLine($"{indent}new CuiCountdownComponent {{ StartTime = {count.StartTime}f, EndTime = {count.EndTime}f, Step = {count.Step}f, Interval = {count.Interval}f, Command = \"{count.Command}\" }},");
                    break;
                case CuiOutlineComponent outline:
                    sb.AppendLine($"{indent}new CuiOutlineComponent {{ Color = \"{outline.Color}\", Distance = \"{outline.Distance}\" }},");
                    break;
                case CuiScrollViewComponent scroll:
                    sb.AppendLine($"{indent}new CuiScrollViewComponent {{ Horizontal = {(scroll.Horizontal ? "true" : "false")}, Vertical = {(scroll.Vertical ? "true" : "false")}, MovementType = ScrollRect.MovementType.{scroll.MovementType} }},");
                    break;
                case CuiNeedsCursorComponent:
                    sb.AppendLine($"{indent}new CuiNeedsCursorComponent(),");
                    break;
                case CuiNeedsKeyboardComponent:
                    sb.AppendLine($"{indent}new CuiNeedsKeyboardComponent(),");
                    break;
                default:
                    sb.AppendLine($"{indent}new {c.GetType().Name}(),");
                    break;
            }
        }

        private static string EscapeCSharp(string str)
        {
            if (string.IsNullOrEmpty(str)) return "";
            return str.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");
        }
    }
}
