using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using RustCUIBuilder.Runtime.Core.Models;

namespace RustCUIBuilder.Runtime.Core.Serialization
{
    public class CodeGeneratorOptions
    {
        public string MethodName { get; set; } = "DrawUI";
        public string AccessModifier { get; set; } = "private";
        public string PlayerParamType { get; set; } = "BasePlayer";
        public string PlayerVariableName { get; set; } = "player";
        public string CustomArguments { get; set; } = "";
        public string ContainerVariableName { get; set; } = "container";
        public string MainPanelConstantName { get; set; } = "MainUiPanel";
        public string ChatCommandName { get; set; } = "menu";
        public string PreCode { get; set; } = "";
        public string PostCode { get; set; } = "";
        public bool IncludeMethodWrapper { get; set; } = true;
        public bool IncludeCommandHook { get; set; } = true;
        public bool IncludeUnloadHook { get; set; } = true;
        public bool UseHighLevelPresets { get; set; } = true;
    }

    /// <summary>
    /// Generates clean, deterministic, valid Oxide/uMod C# plugin code.
    /// Employs CuiElementContainer with high-level CuiPanel, CuiLabel, CuiButton, and individual CuiElement blocks.
    /// </summary>
    public static class CuiCodeGenerator
    {
        public static string GeneratePluginCode(CuiDocument doc, CodeGeneratorOptions options = null)
        {
            options = options ?? new CodeGeneratorOptions();
            var sb = new StringBuilder(4096);

            string rootPanelName = doc.Elements.FirstOrDefault(e => e.Components.Any(c => c is CuiNeedsCursorComponent || c is CuiImageComponent))?.Name ?? "MainPanel";

            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine("//  <auto-generated>");
            sb.AppendLine("//      Rust Oxide CUI Builder Generated Code");
            sb.AppendLine($"//      Rust Protocol: {doc.RustProtocol} | Elements: {doc.Elements.Count}");
            sb.AppendLine("//  </auto-generated>");
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Oxide.Core;");
            sb.AppendLine("using Oxide.Game.Rust.Cui;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.UI;");
            sb.AppendLine();

            if (options.IncludeMethodWrapper)
            {
                sb.AppendLine($"private const string {options.MainPanelConstantName} = \"{rootPanelName}\";");
                sb.AppendLine();

                string argsList = $"{options.PlayerParamType} {options.PlayerVariableName}";
                if (!string.IsNullOrWhiteSpace(options.CustomArguments))
                {
                    argsList += ", " + options.CustomArguments.Trim();
                }

                sb.AppendLine($"{options.AccessModifier} void {options.MethodName}({argsList})");
                sb.AppendLine("{");
                sb.AppendLine($"    if ({options.PlayerVariableName} == null || !{options.PlayerVariableName}.IsConnected) return;");
                sb.AppendLine();

                if (!string.IsNullOrWhiteSpace(options.PreCode))
                {
                    sb.AppendLine("    // Custom Pre-Code");
                    sb.AppendLine("    " + options.PreCode.Trim().Replace("\n", "\n    "));
                    sb.AppendLine();
                }

                sb.AppendLine("    // Clean up any existing UI to avoid stacking");
                sb.AppendLine($"    CuiHelper.DestroyUi({options.PlayerVariableName}, {options.MainPanelConstantName});");
                sb.AppendLine();
                sb.AppendLine($"    var {options.ContainerVariableName} = new CuiElementContainer();");
                sb.AppendLine();
            }

            string indent = options.IncludeMethodWrapper ? "    " : "";

            foreach (var elem in doc.Elements)
            {
                GenerateElementCode(sb, elem, indent, options);
            }

            if (options.IncludeMethodWrapper)
            {
                sb.AppendLine();
                sb.AppendLine($"    CuiHelper.AddUi({options.PlayerVariableName}, {options.ContainerVariableName});");

                if (!string.IsNullOrWhiteSpace(options.PostCode))
                {
                    sb.AppendLine();
                    sb.AppendLine("    // Custom Post-Code");
                    sb.AppendLine("    " + options.PostCode.Trim().Replace("\n", "\n    "));
                }

                sb.AppendLine("}");

                if (options.IncludeCommandHook && !string.IsNullOrWhiteSpace(options.ChatCommandName))
                {
                    sb.AppendLine();
                    sb.AppendLine($"[ChatCommand(\"{options.ChatCommandName.Trim()}\")]");
                    sb.AppendLine($"private void CmdOpenUi(BasePlayer player, string command, string[] args)");
                    sb.AppendLine("{");
                    sb.AppendLine($"    {options.MethodName}(player);");
                    sb.AppendLine("}");
                }

                if (options.IncludeUnloadHook)
                {
                    sb.AppendLine();
                    sb.AppendLine("private void Unload()");
                    sb.AppendLine("{");
                    sb.AppendLine("    foreach (var player in BasePlayer.activePlayerList)");
                    sb.AppendLine("    {");
                    sb.AppendLine($"        CuiHelper.DestroyUi(player, {options.MainPanelConstantName});");
                    sb.AppendLine("    }");
                    sb.AppendLine("}");
                }
            }

            return sb.ToString();
        }

        private static void GenerateElementCode(StringBuilder sb, CuiElementNode elem, string indent, CodeGeneratorOptions options)
        {
            var rect = elem.GetComponent<CuiRectTransformComponent>() ?? new CuiRectTransformComponent();
            var img = elem.GetComponent<CuiImageComponent>();
            var text = elem.GetComponent<CuiTextComponent>();
            var btn = elem.GetComponent<CuiButtonComponent>();
            var raw = elem.GetComponent<CuiRawImageComponent>();
            var count = elem.GetComponent<CuiCountdownComponent>();

            // 1. High level CuiPanel
            if (options.UseHighLevelPresets && img != null && text == null && btn == null && raw == null)
            {
                sb.AppendLine($"{indent}{options.ContainerVariableName}.Add(new CuiPanel");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    Image = new CuiImageComponent");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        Color = \"{img.Color}\",");
                if (!string.IsNullOrEmpty(img.Sprite)) sb.AppendLine($"{indent}        Sprite = \"{img.Sprite}\",");
                if (!string.IsNullOrEmpty(img.Material)) sb.AppendLine($"{indent}        Material = \"{img.Material}\",");
                if (img.ItemId != 0) sb.AppendLine($"{indent}        ItemId = {img.ItemId},");
                sb.AppendLine($"{indent}        FadeIn = {img.FadeIn:0.##}f");
                sb.AppendLine($"{indent}    }},");
                sb.AppendLine($"{indent}    RectTransform = new CuiRectTransformComponent");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        AnchorMin = \"{rect.AnchorMin}\",");
                sb.AppendLine($"{indent}        AnchorMax = \"{rect.AnchorMax}\",");
                if (rect.OffsetMin != "0 0") sb.AppendLine($"{indent}        OffsetMin = \"{rect.OffsetMin}\",");
                if (rect.OffsetMax != "0 0") sb.AppendLine($"{indent}        OffsetMax = \"{rect.OffsetMax}\",");
                sb.AppendLine($"{indent}    }},");
                if (elem.GetComponent<CuiNeedsCursorComponent>() != null) sb.AppendLine($"{indent}    CursorEnabled = true,");
                if (elem.GetComponent<CuiNeedsKeyboardComponent>() != null) sb.AppendLine($"{indent}    KeyboardEnabled = true,");
                if (elem.FadeOut > 0f) sb.AppendLine($"{indent}    FadeOut = {elem.FadeOut:0.##}f");
                sb.AppendLine($"{indent}}}, \"{elem.Parent}\", \"{elem.Name}\");");
                sb.AppendLine();
                return;
            }

            // 2. High level CuiLabel
            if (options.UseHighLevelPresets && text != null && btn == null && img == null)
            {
                string escapedText = (text.Text ?? "").Replace("\"", "\\\"").Replace("\n", "\\n");
                sb.AppendLine($"{indent}{options.ContainerVariableName}.Add(new CuiLabel");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    Text = new CuiTextComponent");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        Text = \"{escapedText}\",");
                sb.AppendLine($"{indent}        FontSize = {text.FontSize},");
                if (!string.IsNullOrEmpty(text.Font)) sb.AppendLine($"{indent}        Font = \"{text.Font}\",");
                sb.AppendLine($"{indent}        Align = TextAnchor.{text.Align},");
                sb.AppendLine($"{indent}        Color = \"{text.Color}\",");
                sb.AppendLine($"{indent}        FadeIn = {text.FadeIn:0.##}f");
                sb.AppendLine($"{indent}    }},");
                sb.AppendLine($"{indent}    RectTransform = new CuiRectTransformComponent");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        AnchorMin = \"{rect.AnchorMin}\",");
                sb.AppendLine($"{indent}        AnchorMax = \"{rect.AnchorMax}\",");
                if (rect.OffsetMin != "0 0") sb.AppendLine($"{indent}        OffsetMin = \"{rect.OffsetMin}\",");
                if (rect.OffsetMax != "0 0") sb.AppendLine($"{indent}        OffsetMax = \"{rect.OffsetMax}\",");
                sb.AppendLine($"{indent}    }},");
                if (elem.FadeOut > 0f) sb.AppendLine($"{indent}    FadeOut = {elem.FadeOut:0.##}f");
                sb.AppendLine($"{indent}}}, \"{elem.Parent}\", \"{elem.Name}\");");
                sb.AppendLine();
                return;
            }

            // 3. High level CuiButton
            if (options.UseHighLevelPresets && btn != null)
            {
                sb.AppendLine($"{indent}{options.ContainerVariableName}.Add(new CuiButton");
                sb.AppendLine($"{indent}{{");
                sb.AppendLine($"{indent}    Button = new CuiButtonComponent");
                sb.AppendLine($"{indent}    {{");
                if (!string.IsNullOrEmpty(btn.Command)) sb.AppendLine($"{indent}        Command = \"{btn.Command}\",");
                if (!string.IsNullOrEmpty(btn.Close)) sb.AppendLine($"{indent}        Close = \"{btn.Close}\",");
                sb.AppendLine($"{indent}        Color = \"{btn.Color}\",");
                if (!string.IsNullOrEmpty(btn.Material)) sb.AppendLine($"{indent}        Material = \"{btn.Material}\",");
                sb.AppendLine($"{indent}        FadeIn = {btn.FadeIn:0.##}f");
                sb.AppendLine($"{indent}    }},");
                if (text != null)
                {
                    string escapedText = (text.Text ?? "").Replace("\"", "\\\"").Replace("\n", "\\n");
                    sb.AppendLine($"{indent}    Text = new CuiTextComponent");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        Text = \"{escapedText}\",");
                    sb.AppendLine($"{indent}        FontSize = {text.FontSize},");
                    sb.AppendLine($"{indent}        Align = TextAnchor.{text.Align},");
                    sb.AppendLine($"{indent}        Color = \"{text.Color}\"");
                    sb.AppendLine($"{indent}    }},");
                }
                sb.AppendLine($"{indent}    RectTransform = new CuiRectTransformComponent");
                sb.AppendLine($"{indent}    {{");
                sb.AppendLine($"{indent}        AnchorMin = \"{rect.AnchorMin}\",");
                sb.AppendLine($"{indent}        AnchorMax = \"{rect.AnchorMax}\",");
                if (rect.OffsetMin != "0 0") sb.AppendLine($"{indent}        OffsetMin = \"{rect.OffsetMin}\",");
                if (rect.OffsetMax != "0 0") sb.AppendLine($"{indent}        OffsetMax = \"{rect.OffsetMax}\",");
                sb.AppendLine($"{indent}    }},");
                if (elem.FadeOut > 0f) sb.AppendLine($"{indent}    FadeOut = {elem.FadeOut:0.##}f");
                sb.AppendLine($"{indent}}}, \"{elem.Parent}\", \"{elem.Name}\");");
                sb.AppendLine();
                return;
            }

            // 4. Default generic CuiElement
            sb.AppendLine($"{indent}{options.ContainerVariableName}.Add(new CuiElement");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    Name = \"{elem.Name}\",");
            sb.AppendLine($"{indent}    Parent = \"{elem.Parent}\",");
            if (elem.FadeOut > 0f) sb.AppendLine($"{indent}    FadeOut = {elem.FadeOut:0.##}f,");
            if (elem.DestroyUi != null) sb.AppendLine($"{indent}    DestroyUi = \"{elem.DestroyUi}\",");
            if (elem.Update) sb.AppendLine($"{indent}    Update = true,");
            sb.AppendLine($"{indent}    Components =");
            sb.AppendLine($"{indent}    {{");

            for (int i = 0; i < elem.Components.Count; i++)
            {
                var comp = elem.Components[i];
                string compCode = GenerateConcreteComponentCode(comp, indent + "        ");
                sb.Append(compCode);
                if (i < elem.Components.Count - 1) sb.AppendLine(",");
                else sb.AppendLine();
            }

            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}});");
            sb.AppendLine();
        }

        private static string GenerateConcreteComponentCode(ICuiComponent comp, string indent)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"{indent}new {comp.GetType().Name}");
            sb.AppendLine($"{indent}{{");

            switch (comp)
            {
                case CuiRectTransformComponent r:
                    sb.AppendLine($"{indent}    AnchorMin = \"{r.AnchorMin}\",");
                    sb.AppendLine($"{indent}    AnchorMax = \"{r.AnchorMax}\",");
                    if (r.OffsetMin != "0 0") sb.AppendLine($"{indent}    OffsetMin = \"{r.OffsetMin}\",");
                    if (r.OffsetMax != "0 0") sb.AppendLine($"{indent}    OffsetMax = \"{r.OffsetMax}\",");
                    if (r.Pivot != "0.5 0.5") sb.AppendLine($"{indent}    Pivot = \"{r.Pivot}\",");
                    if (r.Rotation != 0f) sb.AppendLine($"{indent}    Rotation = {r.Rotation:0.##}f");
                    break;
                case CuiTextComponent t:
                    string escapedText = (t.Text ?? "").Replace("\"", "\\\"").Replace("\n", "\\n");
                    sb.AppendLine($"{indent}    Text = \"{escapedText}\",");
                    sb.AppendLine($"{indent}    FontSize = {t.FontSize},");
                    if (!string.IsNullOrEmpty(t.Font)) sb.AppendLine($"{indent}    Font = \"{t.Font}\",");
                    sb.AppendLine($"{indent}    Align = TextAnchor.{t.Align},");
                    sb.AppendLine($"{indent}    Color = \"{t.Color}\",");
                    sb.AppendLine($"{indent}    FadeIn = {t.FadeIn:0.##}f");
                    break;
                case CuiImageComponent im:
                    sb.AppendLine($"{indent}    Color = \"{im.Color}\",");
                    if (!string.IsNullOrEmpty(im.Sprite)) sb.AppendLine($"{indent}    Sprite = \"{im.Sprite}\",");
                    if (!string.IsNullOrEmpty(im.Material)) sb.AppendLine($"{indent}    Material = \"{im.Material}\",");
                    if (im.ItemId != 0) sb.AppendLine($"{indent}    ItemId = {im.ItemId},");
                    sb.AppendLine($"{indent}    FadeIn = {im.FadeIn:0.##}f");
                    break;
                case CuiRawImageComponent raw:
                    sb.AppendLine($"{indent}    Color = \"{raw.Color}\",");
                    if (!string.IsNullOrEmpty(raw.Url)) sb.AppendLine($"{indent}    Url = \"{raw.Url}\",");
                    if (!string.IsNullOrEmpty(raw.SteamId)) sb.AppendLine($"{indent}    SteamId = \"{raw.SteamId}\",");
                    if (!string.IsNullOrEmpty(raw.Material)) sb.AppendLine($"{indent}    Material = \"{raw.Material}\",");
                    sb.AppendLine($"{indent}    FadeIn = {raw.FadeIn:0.##}f");
                    break;
                case CuiCountdownComponent c:
                    sb.AppendLine($"{indent}    StartTime = {c.StartTime:0.##}f,");
                    sb.AppendLine($"{indent}    EndTime = {c.EndTime:0.##}f,");
                    sb.AppendLine($"{indent}    Step = {c.Step:0.##}f,");
                    sb.AppendLine($"{indent}    Interval = {c.Interval:0.##}f,");
                    sb.AppendLine($"{indent}    TimerFormat = CuiTimerFormat.{c.TimerFormat},");
                    if (!string.IsNullOrEmpty(c.Command)) sb.AppendLine($"{indent}    Command = \"{c.Command}\",");
                    sb.AppendLine($"{indent}    DestroyIfDone = {(c.DestroyIfDone ? "true" : "false")}");
                    break;
                case CuiOutlineComponent outl:
                    sb.AppendLine($"{indent}    Color = \"{outl.Color}\",");
                    sb.AppendLine($"{indent}    Distance = \"{outl.Distance}\",");
                    sb.AppendLine($"{indent}    UseGraphicAlpha = {(outl.UseGraphicAlpha ? "true" : "false")}");
                    break;
                default:
                    // Empty body for flag components
                    break;
            }

            sb.Append($"{indent}}}");
            return sb.ToString();
        }
    }
}
